export const DEPARTMENTMANAGER = 'DEPARTMENTMANAGER';
export const GET_DEPARTMENT = 'GET_DEPARTMENT';
export const GET_DEPARTMENT_PAGE = 'GET_DEPARTMENT_PAGE';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const CHANGE_DEPARTMENT = 'CHANGE_DEPARTMENT';
