export const MENURIGHTSMANAGER = 'MENURIGHTSMANAGER';
export const GET_MENU_RIGHTS = 'GET_MENU_RIGHTS';
export const GET_MENU_RIGHTS_PAGE = 'GET_MENU_RIGHTS_PAGE'; 
export const SET_MENU_RIGHTS = 'SET_MENU_RIGHTS';  //菜单配置
export const CHANGE_MENU_RIGHTS = 'CHANGE_MENU_RIGHTS'; 

export const GET_MENU_SECOND = 'GET_MENU_SECOND'; 